### ISSUE TITLE
Using sqlite adapter with LRU

### ISSUE THREAD

**Issue by Rinse12** [microlinkhq/keyvhq#199]
Hey, thanks for open sourcing this library.

We're interested in using this library to store data that would be accessed over a long period of the time in sqlite, but we don't want the data to grow too big. Ideally something like, `new Keyv(`sqlite://${dbPath}`, {namespace: "cache-items", size: 1000})` would evict least accessed items automatically. Is this possible with the current release?

**Comment by Kikobeats** [comment]
Hello, it seems you want to use keyv as LRU. You can bring your own store adapter on top of sqlite to take control over the size, similar to quick-lru example:

https://keyvhq.js.org/#/?id=storage-adapters
