### ISSUE TITLE
JS.ORG URL in the repo

### ISSUE THREAD

**Issue by indus** [microlinkhq/keyvhq#203]
Hi @Kikobeats - JS.ORG here. You've switched from keyv.js.org to keyvhq.js.org a [year ago](https://github.com/js-org/js.org/pull/8082#issuecomment-1466789670). I was wondering if I could remove the custom page rule that is used for the redirect. But I just saw that you are still promoting the old subdomain:
![image](https://github.com/microlinkhq/keyvhq/assets/2046274/097a0f80-fe2b-40a3-9716-53b5dab7307d)
Could you please change that so there is a chance that sometime in the future the page rule is not needed any more (as pointed out [here](https://github.com/js-org/js.org/pull/8079#issuecomment-1466803477) - they are a limited resource).
Best
Stefan

**Comment by Jytesh** [comment]
Changed, thank you for bringing it to notice :)
