### ISSUE TITLE
Export ioredis from @keyvhq/redis package

### ISSUE THREAD

**Issue by BryceMehring** [microlinkhq/keyvhq#205]
`ioredis` should be exported from the `@keyvhq/redis` package so that we can ensure that we are using the same version of `ioredis` required by this package. On https://github.com/microlinkhq/keyvhq/blob/8712c7b57c3b9614a67182fa14d60c63bb27e936/packages/redis/src/index.js#L7 we are checking if the argument is an `ioredis` Redis instance but that only works if the version is the same.

**Comment by Kikobeats** [comment]
I agree; alternative I can drop ioredis and make it a peer dependency; which solution sounds worst in your opinion?

**Comment by BryceMehring** [comment]
Is https://github.com/microlinkhq/keyvhq/commit/e819f7a1b19d12e25aa63e23379f8b7feab6f3d3 going to be published to npm?
