### ISSUE TITLE
What is the relation between `keyv` and `@keyvhq/keyv` projects?

### ISSUE THREAD

**Issue by michaelrambeau** [microlinkhq/keyvhq#39]
Hello,
I run [Best of JS](https://bestofjs.org/projects/keyv) site where _Keyv_ project is tracked as a repo from Luke Childs.
So it seems there are 2 Keyv projects:

- Original: https://github.com/lukechilds/keyv `keyv` on NPM
- Yours: https://github.com/microlinkhq/keyv `@keyvhq/keyv` on NPM

Same name, almost same logo (blue VS red), same description in the README.md... it's a bit confusing!
Which one is the right `Keyv`? Or what is the relation between both projects?
Sorry if I missed something obvious, I suppose it's a fork because the orginal one might be not maintained but I couldn't find any clarification, the following issue does not explain anything about the reason why moving from `keyv` to `@keyvhq/keyv`.

https://github.com/microlinkhq/keyv/issues/20

Thank you for the clarification.
I hope I will not have to track 2 different `Keyv` projects in _Best of JS_ 😅 !

#### Screenshot (Original)

![image](https://user-images.githubusercontent.com/5546996/129279055-e60c945d-487c-44a5-8858-b5e8df59cbc5.png)

#### Screenshot (Yours)

![image](https://user-images.githubusercontent.com/5546996/129279176-fbf553f0-aa8f-44c4-8070-9508c59a8656.png)

**Comment by Jytesh** [comment]
Hello, keyv by lukechilds is the original project ( last updated in sept 2020 ), the original author become busy with other work, so we forked it to make this repo, I will update the readme and add proper attribution as well

**Comment by Kikobeats** [comment]
> I suppose it's a fork because the original one might be not maintained

Exactly that 🙂

**Comment by mziwisky** [comment]
It looks like the original got picked back up at https://github.com/jaredwray/keyv.  Is there still some delta in functionality that makes it worthwhile to maintain this fork?  If so, is it something that could be merged into that "upstream" repo so this one could be deprecated?  I think it's still confusing to have both of these projects existing.  E.g. when I [google "keyv"](https://www.google.com/search?q=keyv), my first result is [the original package on npmjs.com](https://www.npmjs.com/package/keyv), and my second is [documentation for this project on js.org](https://keyv.js.org/).

**Comment by adamk33n3r** [comment]
Just found this confusing too....which should I use?

**Comment by Kikobeats** [comment]
Both projects are quite different and point. Evaluate them and use whatever you want 🙂
